feat: add page title metadata
programming-in-th/programming.in.th pull request #946
Opened 2024-02-11 13:49 UTC by gxjakkap

#945 

I decided to mostly add title to pages visible to user. Let me know if I missed anything or did anything wrong.🙇🏼‍♂️

Static title:
- /about
- /archive/*
- /assessments/*
- /learn
- /login
- / (Home)
- /submissions/*
- /tasks

Dynamic title:
- /tasks/:id

2024-02-11 14:37 UTC, MasterIceZ requested changes

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/about/page.tsx
> +  title: 'About - programming.in.th'
```suggestion
  title: 'About | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/archive/[[...slug]]/page.tsx
> +  title: 'Archive - programming.in.th'
```suggestion
  title: 'Archive | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/assessments/page.tsx
> +        <title>Assesments - programming.in.th</title>
```suggestion
        <title>Assesments | programming.in.th</title>
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/learn/page.tsx
> +  title: 'Learn - programming.in.th'
```suggestion
  title: 'Learn | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/login/page.tsx
> +  title: 'Login - programming.in.th'
```suggestion
  title: 'Login | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/submissions/[id]/page.tsx
> +  title: 'Submission - programming.in.th'
```suggestion
  title: 'Submission | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/user/page.tsx
> +  title: 'User Dashboard - programming.in.th'
```suggestion
  title: 'Dashboard | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/tasks/page.tsx
> +  title: 'Tasks - programming.in.th'
```suggestion
  title: 'Tasks | programming.in.th'
```

2024-02-11 14:37 UTC, MasterIceZ commented on src/app/tasks/[...id]/page.tsx
> +    title: `${task.title} - programming.in.th`
```suggestion
    title: `${task.title} | programming.in.th`
```

2024-02-12 05:10 UTC, MasterIceZ approved these changes

2024-02-17 16:23 UTC, leomotors approved these changes
lgtm

2024-02-17 16:23 UTC, merged